# Generated by Django 3.2.4 on 2021-07-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='day_slot',
            field=models.CharField(default='tmp', max_length=220),
            preserve_default=False,
        ),
    ]
