# Generated by Django 3.0 on 2021-06-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='received_orders',
            field=models.IntegerField(default=0),
        ),
    ]
