# Generated by Django 3.2.4 on 2021-06-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_hash',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
