# Generated by Django 3.2.4 on 2021-06-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210623_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='n_ordered_products',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
