# Generated by Django 3.2.4 on 2021-06-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210620_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_stamp',
        ),
    ]
