# Generated by Django 3.2.4 on 2021-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_n_ordered_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
