# Generated by Django 3.2.4 on 2021-06-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
    ]
