# Generated by Django 3.2.4 on 2021-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_ordered_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_products',
            field=models.JSONField(default=dict),
        ),
    ]
