# Generated by Django 3.2.4 on 2021-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
